### ISSUE TITLE
[Cloudwatch] 에러 로그 cloudwatch 에 생성되지 않는 버그

### ISSUE THREAD

**Issue by Limdongmoo** [hobbyloop/hobbyloop-be#98]
- 기존 enumtype binding 관련 에러 로그는 cloudwatch 에 정상적으로 업로드되지만 login 관련 에러 로그가 설정해놨음에도 cloudwatch 에 올라가지 않음

**Comment by Limdongmoo** [comment]
- GlobalExceptionHandler 에서 로그 찍는 부분을 삭제했을 때도 로그를 남김
```java
	/**
	 * enum Type 불일치 Exception
	 */
	@ExceptionHandler(EnumTypeBindingException.class)
	protected ResponseEntity<ExceptionResponse> handleEnumTypeBinding(EnumTypeBindingException error) {
		ExceptionResponse exceptionResponse = ExceptionResponse.from(error);
		return new ResponseEntity<>(exceptionResponse, exceptionResponse.getStatus());
	}
```
---
### - 에러 메시지 
```
2023-07-10 14:57:21.756 ERROR 56638 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception

hobbyloop.backend.domain.exception.enumbinding.enumtype.SocialTypeBindingException: 요청에 대한 SOCIAL Enum Type 을 찾을 수 없음
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at hobbyloop.backend.domain.user.SocialType.of(SocialType.java:57)
	at hobbyloop.backend.api.infra.global.oauth2.filter.OAuth2AccessTokenAuthenticationFilter.attemptAuthentication(OAuth2AccessTokenAuthenticationFilter.java:51)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:227)
	at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at hobbyloop.backend.api.infra.global.jwt.filter.JwtAuthenticationProcessingFilter.checkAccessTokenAndAuthentication(JwtAuthenticationProcessingFilter.java:116)
	at hobbyloop.backend.api.infra.global.jwt.filter.JwtAuthenticationProcessingFilter.doFilterInternal(JwtAuthenticationProcessingFilter.java:68)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:103)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:89)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:90)
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:75)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:112)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:82)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:55)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.session.DisableEncodeUrlFilter.doFilterInternal(DisableEncodeUrlFilter.java:42)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:346)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:221)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:186)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:891)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1784)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Limdongmoo** [comment]
## - 확인해보니 로그를 찍는 주체가 다름

- cloudwatch 에 올라가는 에러 주체 : GlobalExceptionHandler
``` 
2023-07-10 14:48:00.343 ERROR 56089 --- [nio-8080-exec-2] h.b.a.c.util.GlobalExceptionHandler      : HANDLE ERROR - hobbyloop.backend.domain.exception.enumbinding.enumtype.TicketTypeBindingException: 요청에 대한 Ticket Enum Type 을 찾을 수 없음
```
- cloudwatch 에 올라가지 않는 에러 주체  : 
```
2023-07-10 14:57:21.756 ERROR 56638 --- [nio-8080-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
```
---

현재 cloudwatch 에 올라가지 않는 SocialTypeBindingException 의 경우 로그를 
GlobalExceptionHandler 가 아닌 dispatcherServlet 에서 로그를 발생시키며, 
해당 로그 내에 SocialTypeBindingException 메시지가 포함된 형태

**Comment by Limdongmoo** [comment]
## - 해결
### 1. 기존 패키지명으로 로그가 올라가지 않던 문제
```xml
        <logger name="hoobyloop.backend.api" level="info" additivity="false">
            <appender-ref ref="aws_cloud_watch_log"/>
        </logger>
```
- 단순한 오타 문제 : hoobyloop -> hobbyloop
- 문제 해결로 GlobalExceptionHandler 에서 던지는 예외메시지를 따로 처리할 필요가 없어져서 해당 부분 삭제
- 삭제한 부분
```xml
        <logger name="hobbyloop.backend.api.controller.util.GlobalExceptionHandler" level="warn" additivity="false">
            <appender-ref ref="aws_cloud_watch_log"/>
        </logger>

        <logger name="hobbyloop.backend.api.controller.util.GlobalExceptionHandler" level="error" additivity="false">
            <appender-ref ref="aws_cloud_watch_log"/>
        </logger>
```

### 2. cloudwatch 에 올라가지 않는 에러 처리
- root level 을 info 로 설정하고, 모든 로그를 console 과 cloudwatch 에 올라가도록 설정
- "aws_cloud_watch_log" appender 에서 WARN 이상의 로그 (WARN, ERROR) 로 지정해줬기에 info 로그는 cloudwatch에 올라가지 않음

- TO BE
```xml
   <springProfile name="prod">
        <root level="info">
            <appender-ref ref="aws_cloud_watch_log"/>
            <appender-ref ref="CONSOLE"/>
        </root>

        <logger name="java.sql" level="warn" additivity="false">
            <appender-ref ref="CONSOLE"/>
        </logger>

        <logger name="jdbc" level="error" additivity="false">
            <appender-ref ref="CONSOLE"/>
        </logger>

        <logger name="org.hibernate.SQL" level="warn" additivity="false">
            <appender-ref ref="CONSOLE"/>
        </logger>

        <logger name="com.zaxxer.hikari.HikariDataSource" level="info" additivity="false">
            <appender-ref ref="CONSOLE"/>
        </logger>

        <logger name="com.amazonaws.util.EC2MetadataUtils" level="error" additivity="false">
        </logger>

    </springProfile>
```

- 결과 
<img src="https://github.com/hobbyloop/hobbyloop-be/assets/99455667/4989792d-20f7-40d7-83b0-f8e6cb936bd2" width="45%"><img src="https://github.com/hobbyloop/hobbyloop-be/assets/99455667/599a3622-ae14-4a46-9baa-d7d2e427cade" width="45%">
